Traning/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token



urlpatterns = [

    path('login/', include('boards.urls')),
    path('admin/', admin.site.urls),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

]

boards/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views
urlpatterns = [

path('home/',views.home,name='home'),
path('get/<pk>/',views.board_topics,name='border_topic'),
path('add/<pk>/new',views.new_topic,name='new_topic'),
path('update/',views.update,name='update'),
#path('board/',views.BoardList.as_view(),name='django_rest'),

path('creat/',views.creat_board,name='create_board'),
path('update/<str:pk>/',views.UpdateBoard,name='Update_Board'),
path('delete/<str:pk>/',views.DeleteBoard,name='Delete_Board'),


path('list/',views.boardList,name='BoardList'),
path('Create/',views.boardCreate,name='BoardCreate'),
path('UpdateBoard/<str:pk>',views.boardUpdate,name='BoardUpdate'),
path('DeleteBoard/<str:pk>',views.boardDelete,name='BoardDelete'),

path('',views.user_login,name='login'),
path('logout/',views.user_logout,name='logout'),

path('hello/',views.HelloView.as_view(),name='hello'),
    ]

boards/models.py
from django.db import models
from django.contrib.auth.models import User

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board,models.CASCADE, related_name='topics')
    starter = models.ForeignKey(User,models.CASCADE, related_name='topics')
    
class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic,models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User,models.CASCADE, related_name='posts')
    updated_by = models.ForeignKey(User,models.CASCADE, null=True, related_name='+')
# Create your models here.

boards/forms.py
from  django.forms import ModelForm
from .models import Board

class BoardForm(ModelForm):

    class Meta:
        model=Board
        fields='__all__'

boards/views.py
from django.contrib.auth.models import User
from .models import  Board,Topic,Post
from django.views import View
# Create your views here.
from django.shortcuts import render, get_object_or_404,redirect,HttpResponseRedirect,reverse
from django.views.decorators.http import require_http_methods
from rest_framework.decorators import api_view

from  rest_framework.views import  APIView
from .serializers import  BoardSerializ
from rest_framework.response import Response
from rest_framework import status
from .forms import BoardForm
from django.contrib.auth import authenticate,login,logout
from rest_framework.permissions import IsAuthenticated


def user_login(request):
    context={}
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(request,username=username,password=password)
        if user:
            login(request,user)
            return HttpResponseRedirect(reverse('home'))

        else:
            context["error"]="provide valid credentials!"
            return render(request, 'login.html', context)

    else:
        return render(request,'login.html',context)


def user_logout(request):
     logout(request)
     return HttpResponseRedirect(reverse('login'))



class HelloView(APIView):
    permission_classes = (IsAuthenticated,)             # <-- And here
    def get(self, request):
        content = {'message': 'Hello, World!'}
        return Response(content)
@require_http_methods(['GET'])
def home(request):
    boards=Board.objects.all()
    return render(request,'home.html',{'boards':boards})




def board_topics(request,pk):
         board = get_object_or_404(Board, pk=pk)
         return render(request, 'topics.html', {'board': board})






def new_topic(request,pk):
    board=get_object_or_404(Board,pk=pk)
    user=User.objects.first()
    if request.method=='POST':
        subject=request.POST['subject']
        message=request.POST['message']

        topic=Topic.objects.create(
        subject=subject,
        board=board,
        starter=user
         )
        post=Post.objects.create(
        message=message,
        topic=topic,
        created_by=user
        )

    return render(request,'new_topic.html',{'board':board})


def update(request):
    board=Board.objects.all().update( description='This ....')
    return redirect('home')



@api_view(['GET'])
def boardList(request):
     board=Board.objects.all()
     serializer=BoardSerializ(board,many=True)
     return Response(serializer.data)


@api_view(['POST'])
def boardCreate(request):
    serializer=BoardSerializ(data=request.data)
    serializer.validate_name(request.data['name'])
    if serializer.is_valid(raise_exception=True):
        serializer.save()

    return Response (serializer.data)



@api_view(['PUT'])
def boardUpdate(request,pk):
    board=Board.objects.get(id=pk)
    serializer=BoardSerializ(instance=board,data=request.data)
    if serializer.is_valid():
        serializer.save()
    return Response (serializer.data)

@api_view(['delete'])
def boardDelete(request,pk):
    board=Board.objects.filter(id=pk).first()
    board.delete()
    return Response ('Deleted!')












def creat_board(request):
    form = BoardForm()
    if request.method=='POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context={'form':form}
    return render(request,'new_board.html',context)

def UpdateBoard(request,pk):
    board=Board.objects.get(id=pk)
    form = BoardForm(instance=board)
    if request.method=='POST':
        form = BoardForm(request.POST,instance=board)
        if form.is_valid():
            form.save()
            return redirect('/')

    context={'form':form}

    return render(request, 'new_board.html', context)


def DeleteBoard(request,pk):
    board = Board.objects.get(id=pk)
    if request.method=='POST':
        board.delete()
        return redirect('/')

    context={'item':board}
    return render(request,'delete.html',context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
 <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
      </div>
    </nav>

    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/delete.html
{%extends 'base.html'%}

{% block content %}
<p>Are you sure to delete"{{item}}"?</p>
<form action="{%url 'Delete_Board' item.id%}" method="POST">
       {% csrf_token %}
      <a href="{% url 'home' %}">Cancel</a>
<input type="submit"  name="Confirm">
</form>

      {% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
<button ><a class=""btn btn-primary href="{% url 'create_board' %}">Craete New Board</a></button><br><br>
<button><a class=""btn btn-primary href="{% url 'BoardCreate' %}">Craete REST API</a></button>

<br>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            {{ board.name }}
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td></td>
          <td><button><a href="{%url 'Update_Board' board.id %}">Update</a></button><br><br>
         <button><a href="{%url 'BoardUpdate' board.id %}">Update REST API</a></button ></td>
          <td><button><a href="{%url 'Delete_Board' board.id %}">Delete</a></button><br><br>
       <button>  <a href="{%url 'BoardDelete' board.id %}">Delete REST API</a></button>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>


<a href="{% url 'logout'%}">LOGOUT</a>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
  {% block content %}

<form method="post">
    {% csrf_token%}
    <table>
       <tr>
           <td>  <label for="username"> Username</label></td>
           <td> <input type="text" name="username"  id="username"> </td>


       </tr>

         <tr>
           <td>  <label for="password"> Password</label></td>
           <td> <input type="text" name="password"  id="password"> </td>


       </tr>
        <p> {{error}} </p>
    </table>

    <button type="submit">Login</button>
</form>



 {% endblock %}

templates/new_board.html
{%extends 'base.html'%}
{% block content %}
<form method="POST">
 {% csrf_token %}
{{form}}
    <button type="submit" class="btn btn-success">Submit</button>




</form>



      {% endblock %}

templates/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="http://127.0.0.1:8000/home/">Boards</a></li>
<li class="breadcrumb-item"><a href="http://127.0.0.1:8000/home/">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subject">Subject</label>
      <input type="text" class="form-control" id="id_subject" name="subject">
    </div>
    <div class="form-group">
      <label for="id_message">Message</label>
      <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Post</button>
  </form>


{% endblock %}

templates/topics.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="http://127.0.0.1:8000/home/">Boards</a></li>
  <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
    <!-- just leaving it empty for now. we will add core here soon. -->
{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
<h1>Update is Done !</h1>

{% endblock %}